apiVersion: v1
kind: Service
metadata:
  name: argocd-loadbalancer-guestbook-demo
  labels:
    app: guestbook-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: guestbook-ui
