apiVersion: v1
kind: Service
metadata:
  name: argocd-server-loadbalancer
  labels:
    app: guestbook-ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
