apiVersion: v1
kind: Service
metadata:
  name: argocd-server-loadbalancer
  namespace: testing
  labels:
    app: helm-guestbook
    release: helm-guestbook
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helm-guestbook
    release: helm-guestbook
