---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-arm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-demo-arm
  template:
    metadata:
      labels:
        app: nginx-demo-arm
    spec:
      containers:
        - image: callumhoughton22/doom-in-docker:0.1 #nginxdemos/hello
          name: nginx-demo-arm
          ports:
            - containerPort: 80