# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-demo-arm
# spec:
#   ports:
#     - port: 80
#       targetPort: 80
#   selector:
#     app: nginx-demo-arm

apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-arm
  namespace: argocd
  labels:
    app: nginx-demo-arm
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-demo-arm
