apiVersion: v1
kind: Namespace
metadata:
  name: argocd-demo
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-arm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: nginx #ghcr.io/theautomationrules/nginx-demo-arm:0.1.0
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: argocd-demo
  source:
    repoURL: https://github.com/Cristianguerrer/kubernetes.git
    targetRevision: HEAD
    path: example-manifest/nginx-demo/kustomize/overlays/testing
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true