#Permisos basado en roles
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, repositories, get, */*, allow
    p, role:readonly, clusters, get, */*, allow
    p, role:readonly, projects, get, */*, allow
    g, user1, role:readonly
  policy.default: role:readonly
